const T=['int','wit','emo','ideal','prag','amb','skept','chaos','moral','cur','agency','dark'];
const questions=[
['You have a completely free afternoon. What sounds best?',[['Going somewhere I have never been',{cur:3,chaos:1,agency:1}],['Seeing whoever happens to be around',{emo:2,wit:2,chaos:1}],['Finally doing something I have been putting off',{prag:3,agency:2}],['Staying in and disappearing into something interesting',{int:2,cur:2}],['Making a loose plan, then changing it if something better comes up',{prag:1,chaos:2,cur:2}]]],
['Which person are you most likely to remember after a party?',[['The one who made me laugh',{wit:3,chaos:1}],['The one I could not quite figure out',{cur:3,skept:2}],['The one who seemed completely at ease',{agency:2,amb:2}],['The one I ended up having a proper conversation with',{emo:2,int:2}],['The one who somehow became the centre of everything',{amb:2,wit:1,chaos:2}]]],
['A plan suddenly falls apart. Your first instinct is to…',[['Find another way to make it work',{agency:3,prag:3}],['See what everyone else wants to do',{emo:2,prag:1}],['Laugh and improvise',{wit:2,chaos:3}],['Work out what actually went wrong',{int:2,cur:2,skept:1}],['Wonder whether the new situation might be better',{ideal:2,chaos:2,cur:1}]]],
['Which small annoyance gets to you most?',[['People being confidently wrong',{skept:3,wit:1}],['Being rushed into a decision',{int:2,prag:2}],['People not saying what they mean',{skept:2,emo:2}],['Rules that seem pointless',{agency:2,ideal:2}],['Being left out of the loop',{cur:2,emo:2}]]],
['Pick a quality you tend to appreciate in other people.',[['Quick thinking',{wit:2,agency:2}],['Reliability',{emo:2,prag:2,ideal:1}],['Originality',{cur:2,chaos:2}],['Drive',{amb:3,agency:2}],['Self-awareness',{int:3,moral:1}]]],
['Someone tells you an unbelievable story. You…',[['Want every detail',{cur:3}],['Immediately look for holes in it',{skept:3,prag:1}],['Enjoy the story whether or not it is true',{chaos:2,wit:2}],['Mostly watch how they tell it',{int:2,skept:1,emo:1}],['Ask what happened next',{cur:2,agency:1}]]],
['Which kind of challenge sounds least tedious?',[['Solving something with no obvious answer',{cur:3,int:2}],['Convincing a stubborn person',{wit:2,agency:2}],['Organising a mildly chaotic group',{prag:2,agency:2,chaos:1}],['Learning something difficult from scratch',{amb:2,cur:2}],['Helping two people sort out a disagreement',{emo:3,moral:1}]]],
['You realise you have made the wrong call. What matters next?',[['Correcting it quickly',{agency:3,prag:2}],['Understanding why I got it wrong',{int:3,moral:1}],['Owning it with the people affected',{emo:3,ideal:1}],['Making sure it does not happen again',{prag:3,skept:1}],['Whether the mistake opened up another possibility',{chaos:2,cur:2}]]],
['What makes a conversation especially enjoyable?',[['Someone who can keep up with me',{wit:3}],['Going off on unexpected tangents',{chaos:2,cur:2}],['Getting past the usual small talk',{int:2,emo:2}],['Disagreeing without it becoming unpleasant',{moral:2,wit:1}],['Coming away with a completely new perspective',{cur:3,ideal:1}]]],
['You are handed responsibility for something important. How does that feel?',[['Good — I like having some control',{agency:3,amb:2}],['Fine, once I know exactly what is expected',{prag:3}],['A little daunting, but satisfying',{ideal:2,amb:1,agency:1}],['I immediately think about what could go wrong',{skept:2,int:2}],['It depends entirely on who else is involved',{emo:2,prag:1}]]],
['Which situation would make you most curious?',[['Two people remembering the same event differently',{skept:3,int:2}],['Someone unexpectedly changing their mind',{cur:2,int:2}],['A very unlikely coincidence',{chaos:2,cur:3}],['A person succeeding when nobody expected them to',{amb:2,ideal:2}],['A friendship between two very different people',{emo:3,cur:1}]]],
['If you could be unusually good at one thing, which would you choose?',[['Reading a room',{wit:2,emo:2,skept:1}],['Making difficult decisions',{agency:3,prag:2}],['Spotting what everyone else has missed',{cur:2,skept:3}],['Getting people excited about an idea',{amb:2,ideal:2,wit:1}],['Staying calm when everything gets messy',{prag:2,chaos:2}]]],
['Which statement feels closest to you?',[['People are usually more complicated than they first appear',{int:3,moral:2}],['Timing changes almost everything',{prag:2,chaos:2}],['You sometimes have to make your own opportunity',{agency:3,amb:2}],['A good sense of humour fixes more than people admit',{wit:3,chaos:1}],['The interesting part is usually what nobody expected',{cur:3,chaos:2}]]],
['When something has been bothering you, what helps most?',[['Talking it through with someone',{emo:3}],['Having enough time to think about it',{int:3}],['Doing something practical about it',{agency:3,prag:2}],['Distracting myself and returning to it later',{chaos:1,prag:1}],['Finding out what I did not know before',{cur:2,skept:2}]]],
['Pick the ending to an evening that sounds most satisfying.',[['Everyone stays much later than planned',{chaos:3,emo:2}],['I leave with something new to think about',{int:2,cur:3}],['Something I had been worrying about is finally settled',{prag:3,emo:1}],['I somehow end up with a story I will be telling for years',{chaos:2,wit:2,cur:1}],['I feel unexpectedly motivated to do something next',{agency:2,ideal:2,amb:1}]]]
];
const plays=[
{name:'Much Ado About Nothing',genre:"Comedy",icon:"masks",p:{int:48,wit:96,emo:78,ideal:67,prag:58,amb:30,skept:60,chaos:72,moral:46,cur:55,agency:66,dark:12},sig:['wit','emo','chaos'],desc:'Sharp conversation, bruised pride and complicated affection are likely to be your sort of fun.'},
{name:'Twelfth Night',genre:"Comedy",icon:"jester",p:{int:62,wit:88,emo:80,ideal:66,prag:42,amb:28,skept:55,chaos:91,moral:57,cur:67,agency:54,dark:22},sig:['wit','chaos','emo'],desc:'You seem well matched to its wit, shifting identities and mixture of warmth and disorder.'},
{name:"A Midsummer Night's Dream",genre:"Comedy",icon:"moon",p:{int:36,wit:73,emo:67,ideal:72,prag:25,amb:20,skept:30,chaos:98,moral:40,cur:78,agency:50,dark:8},sig:['chaos','cur','wit'],desc:'Its playful unpredictability and constantly changing situations fit your appetite for surprise.'},
{name:'As You Like It',genre:"Comedy",icon:"forest",p:{int:58,wit:82,emo:75,ideal:79,prag:45,amb:22,skept:42,chaos:67,moral:49,cur:64,agency:65,dark:8},sig:['wit','ideal','emo'],desc:'Its conversational humour, reinvention and easygoing curiosity should suit you well.'},
{name:'The Tempest',genre:"Romance",icon:"ship",p:{int:78,wit:45,emo:67,ideal:62,prag:55,amb:52,skept:58,chaos:58,moral:82,cur:82,agency:73,dark:38},sig:['int','cur','moral'],desc:'You may enjoy its unusual atmosphere, questions about control and reflective streak.'},
{name:'The Winter’s Tale',genre:"Romance",icon:"bear",p:{int:73,wit:45,emo:88,ideal:74,prag:38,amb:35,skept:70,chaos:55,moral:78,cur:66,agency:45,dark:48},sig:['emo','moral','int'],desc:'Its changes of mood, damaged trust and eventual transformation align with your profile.'},
{name:'Measure for Measure',genre:"Problem Play",icon:"scales",p:{int:82,wit:48,emo:58,ideal:38,prag:64,amb:61,skept:83,chaos:43,moral:98,cur:70,agency:65,dark:62},sig:['moral','skept','int'],desc:'You look receptive to messy decisions, questionable motives and situations without easy answers.'},
{name:'Hamlet',genre:"Tragedy",icon:"skull",p:{int:100,wit:62,emo:78,ideal:43,prag:31,amb:42,skept:96,chaos:40,moral:96,cur:94,agency:28,dark:88},sig:['int','skept','cur','moral'],desc:'Your reflective and questioning side points toward Shakespeare’s most famous puzzle of motives and choices.'},
{name:'Macbeth',genre:"Tragedy",icon:"crown",p:{int:72,wit:24,emo:61,ideal:20,prag:69,amb:100,skept:68,chaos:49,moral:91,cur:62,agency:91,dark:100},sig:['amb','agency','moral'],desc:'Its momentum, ambition and consequences should appeal if you like watching decisive choices gather force.'},
{name:'Othello',genre:"Tragedy",icon:"handkerchief",p:{int:85,wit:38,emo:96,ideal:43,prag:48,amb:42,skept:100,chaos:35,moral:88,cur:69,agency:55,dark:94},sig:['emo','skept','int'],desc:'Trust, interpretation and intense relationships are central here, matching several of your strongest signals.'},
{name:'King Lear',genre:"Tragedy",icon:"storm",p:{int:92,wit:34,emo:95,ideal:30,prag:38,amb:64,skept:73,chaos:51,moral:93,cur:55,agency:48,dark:100},sig:['emo','int','moral'],desc:'Its emotional scale and difficult questions may suit you if you like stories that keep unfolding after the obvious conflict.'},
{name:'Romeo and Juliet',genre:"Tragedy",icon:"roses",p:{int:55,wit:55,emo:100,ideal:92,prag:20,amb:18,skept:30,chaos:56,moral:48,cur:45,agency:78,dark:78},sig:['emo','ideal','agency'],desc:'You appear responsive to emotional commitment, momentum and people acting wholeheartedly on what matters to them.'},
{name:'Julius Caesar',genre:"Tragedy",icon:"dagger",p:{int:72,wit:35,emo:55,ideal:47,prag:82,amb:88,skept:79,chaos:43,moral:90,cur:58,agency:82,dark:70},sig:['moral','prag','amb'],desc:'Competing judgements, persuasion and the consequences of public decisions fit your more strategic side.'},
{name:'Richard III',genre:"History",icon:"boar",p:{int:60,wit:78,emo:24,ideal:12,prag:86,amb:100,skept:74,chaos:55,moral:89,cur:58,agency:100,dark:84},sig:['amb','agency','wit'],desc:'You may enjoy its relentless momentum and a central character who treats social life like a game of strategy.'},
{name:'Henry V',genre:"History",icon:"fleur",p:{int:52,wit:50,emo:55,ideal:70,prag:82,amb:82,skept:42,chaos:35,moral:62,cur:40,agency:96,dark:45},sig:['agency','prag','amb'],desc:'Its emphasis on decisions, leadership and getting people moving may fit your practical, action-oriented side.'},
{name:'Henry IV, Part 1',genre:"History",icon:"tankard",p:{int:58,wit:84,emo:60,ideal:48,prag:70,amb:76,skept:55,chaos:68,moral:63,cur:55,agency:74,dark:42},sig:['wit','amb','chaos'],desc:'Its mix of humour, responsibility and competing ways to live gives you several routes into the play.'},
{name:'Richard II',genre:"History",icon:"crown2",p:{int:89,wit:55,emo:74,ideal:45,prag:43,amb:80,skept:66,chaos:28,moral:77,cur:50,agency:38,dark:58},sig:['int','amb','moral'],desc:'You may connect with its reflective approach to status, identity and what happens when certainty begins to slip.'},
{name:'Coriolanus',genre:"Tragedy",icon:"shield",p:{int:61,wit:25,emo:52,ideal:44,prag:72,amb:88,skept:72,chaos:30,moral:82,cur:43,agency:94,dark:68},sig:['agency','amb','moral'],desc:'Strong wills, difficult compromises and friction between the individual and the group may hold your attention.'},
{name:'Antony and Cleopatra',genre:"Tragedy",icon:"asp",p:{int:70,wit:54,emo:98,ideal:63,prag:48,amb:82,skept:55,chaos:60,moral:76,cur:55,agency:78,dark:72},sig:['emo','amb','agency'],desc:'Its blend of personal attachment, status and impulsive decisions fits an emotionally energetic profile.'},
{name:'The Comedy of Errors',genre:"Comedy",icon:"twins",p:{int:20,wit:80,emo:42,ideal:45,prag:25,amb:15,skept:35,chaos:100,moral:25,cur:60,agency:55,dark:3},sig:['chaos','wit'],desc:'You may simply have a good time with its speed, confusion and escalating absurdity.'},
{name:'The Merchant of Venice',genre:"Comedy",icon:"scales2",p:{int:72,wit:70,emo:67,ideal:48,prag:67,amb:56,skept:70,chaos:42,moral:94,cur:55,agency:66,dark:55},sig:['moral','int','wit'],desc:'Its uneasy mixture of wit, bargains, loyalty and moral tension matches a profile that does not need everything neatly resolved.'},
{name:'The Taming of the Shrew',genre:"Comedy",icon:"sparks",p:{int:42,wit:91,emo:55,ideal:28,prag:60,amb:58,skept:48,chaos:75,moral:72,cur:45,agency:86,dark:24},sig:['wit','agency','chaos'],desc:'Fast verbal sparring and strong personalities may make this one especially engaging for you.'},
{name:'Troilus and Cressida',genre:"Problem Play",icon:"helmet",p:{int:82,wit:72,emo:58,ideal:10,prag:65,amb:66,skept:96,chaos:53,moral:96,cur:68,agency:58,dark:72},sig:['skept','moral','int'],desc:'Your sceptical side may appreciate this strange, cynical play that keeps undermining easy expectations.'},
{name:'Titus Andronicus',genre:"Tragedy",icon:"blade",p:{int:45,wit:28,emo:75,ideal:12,prag:55,amb:58,skept:45,chaos:78,moral:78,cur:42,agency:92,dark:100},sig:['agency','chaos','dark'],desc:'If you enjoy stories that commit fully to escalation and consequence, this is Shakespeare at his most extreme.'}
];
let idx=0,scores=Object.fromEntries(T.map(t=>[t,0])),max=Object.fromEntries(T.map(t=>[t,0]));
for(const q of questions)for(const [,s] of q[1])for(const [k,v] of Object.entries(s))max[k]+=v;
const app=document.querySelector('#app');
const iconMap={
 moon:'☾',ship:'⛵',skull:'☠',masks:'◐',jester:'♢',forest:'♣',bear:'❦',scales:'⚖',crown:'♛',handkerchief:'◇',storm:'ϟ',roses:'❀',dagger:'†',boar:'♞',fleur:'⚜',tankard:'♜',crown2:'♚',shield:'⛨',asp:'§',twins:'♊',scales2:'⚖',sparks:'✦',helmet:'♟',blade:'⚔'};
function art(play,large=false){return `<div class="play-art ${large?'large':''} genre-${play.genre.toLowerCase().replace(/\s/g,'-')}"><span>${iconMap[play.icon]||'✦'}</span><i></i></div>`}
function shell(content,active=''){return `<header class="masthead"><div class="curtain top"></div><div class="brand"><div class="masks">◐ ◑</div><div><h1>Which Shakespeare Play Should You Try?</h1><p>Discover the play that matches your mindset, values and vibe.</p></div></div><nav><button data-nav="start" class="${active==='start'?'active':''}">Start</button><button data-nav="questions" class="${active==='questions'?'active':''}">Questions</button><button data-nav="result" class="${active==='result'?'active':''}" ${!window.lastRanked?'disabled':''}>Your Result</button><button data-nav="plays" class="${active==='plays'?'active':''}">All Plays</button></nav></header><main class="stage">${content}</main><footer>“All the world’s a stage.” <span>— As You Like It</span></footer>`}
function bindNav(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='start')renderStart();else if(n==='questions'){idx=0;scores=Object.fromEntries(T.map(t=>[t,0]));renderQuestion()}else if(n==='result'&&window.lastRanked)renderResult(window.lastRanked);else if(n==='plays')renderAllPlays()})}
function renderStart(){app.innerHTML=shell(`<section class="hero parchment"><div class="eyebrow">15 questions · about 3 minutes</div><h2>Find your Shakespeare match</h2><p>A quick personality quiz with deliberately ambiguous everyday questions. Pick what feels most natural; there are no right answers and no obvious route to a particular play.</p><button class="primary" id="start">Begin the quiz</button><p class="small">No sign-in or data collection. Your answers stay in this browser session.</p></section>`,'start');bindNav();document.querySelector('#start').onclick=()=>{idx=0;scores=Object.fromEntries(T.map(t=>[t,0]));renderQuestion()}}
function renderQuestion(){const [q,answers]=questions[idx];app.innerHTML=shell(`<section class="question parchment"><div class="meta"><span>Question ${idx+1} of ${questions.length}</span><span>${Math.round(idx/questions.length*100)}%</span></div><div class="progress-wrap"><div class="progress" style="width:${idx/questions.length*100}%"></div></div><h2>${q}</h2><div class="answers">${answers.map((a,i)=>`<button class="answer" data-i="${i}"><span>${String.fromCharCode(65+i)}</span>${a[0]}</button>`).join('')}</div></section>`,'questions');bindNav();document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>choose(+b.dataset.i))}
function choose(i){for(const [k,v] of Object.entries(questions[idx][1][i][1]))scores[k]+=v;idx++;idx<questions.length?renderQuestion():finishQuiz()}
function userProfile(){let u={};for(const t of T)u[t]=max[t]?Math.min(100,(scores[t]/(max[t]*.34))*100):45;u.dark=Math.min(100,Math.max(5,(u.moral*.42+u.int*.28+u.skept*.18+u.chaos*.12)-12));return u}
function compatibility(play,u){let weighted=0,weights=0;for(const t of T){let w=play.sig.includes(t)?1.55:1;if(t==='dark')w=.55;weighted+=w*Math.abs(u[t]-play.p[t]);weights+=w}return 1-weighted/(weights*100)}
function finishQuiz(){const u=userProfile();window.lastRanked=plays.map(p=>({...p,match:compatibility(p,u)})).sort((a,b)=>b.match-a.match);renderResult(window.lastRanked)}
function resultCard(p){return `<article class="mini-play">${art(p)}<div><h3>${p.name}</h3><span class="genre ${p.genre.toLowerCase().replace(/\s/g,'-')}">${p.genre}</span><p>${p.desc}</p></div></article>`}
function renderResult(ranked){const top=ranked[0],alts=ranked.slice(1,4);app.innerHTML=shell(`<section class="result parchment"><div class="ribbon">Your Shakespearean Match</div><div class="feature"><div class="feature-art">${art(top,true)}</div><div class="feature-copy"><h2>${top.name}</h2><span class="genre ${top.genre.toLowerCase().replace(/\s/g,'-')}">${top.genre}</span><p>${top.desc}</p><p class="result-note">Your recommendation comes from the overall pattern of your 15 answers rather than a single choice.</p></div></div><div class="divider"><span>Other close matches</span></div><div class="close-matches">${alts.map(resultCard).join('')}</div><div class="result-actions"><button class="primary" id="all">View All Plays</button><button class="ghost" id="again">Take it again</button></div></section>`,'result');bindNav();document.querySelector('#again').onclick=renderStart;document.querySelector('#all').onclick=renderAllPlays}
function renderAllPlays(){const order=['Comedy','Tragedy','History','Romance','Problem Play'];const cards=plays.slice().sort((a,b)=>order.indexOf(a.genre)-order.indexOf(b.genre)||a.name.localeCompare(b.name)).map(p=>`<article class="play-card">${art(p)}<h3>${p.name}</h3><span class="genre ${p.genre.toLowerCase().replace(/\s/g,'-')}">${p.genre}</span><p>${p.desc}</p></article>`).join('');app.innerHTML=shell(`<section class="catalogue"><div class="catalogue-head parchment"><div class="eyebrow">The company of plays</div><h2>All ${plays.length} recommendations</h2><p>Browse every play currently included in the quiz. Genre labels are used in place of compatibility percentages.</p></div><div class="play-grid">${cards}</div></section>`,'plays');bindNav()}
renderStart();
